/* Auto-generated by export_data.py — do not edit by hand. */
window.CATALYST_DATA = {
  "generated_at": "2026-05-23T12:02:35.490043+00:00",
  "run_computed_at": "2026-05-21T02:09:58.666421+00:00",
  "counts": {
    "news_events": 7,
    "classifications": 7,
    "live_signals": 3,
    "suppressed": 1,
    "caution": 2,
    "clear": 0
  },
  "signals": [
    {
      "asset": "BTC",
      "window_start": "2026-05-21T02:01:11.486914+00:00",
      "window_end": "2026-05-24T02:09:58.644313+00:00",
      "risk_score": 0.9155,
      "recommendation": "SUPPRESS",
      "active_categories": [
        "macro"
      ],
      "computed_at": "2026-05-21T02:09:58.666421+00:00",
      "contributing": [
        {
          "external_id": "https://decrypt.co/?p=368321",
          "title": "Bitcoin ETFs Shed $649M in a Day as Long-Term BTC Holders \u2018Limit Downside Potential\u2019",
          "source": "Decrypt",
          "url": "https://decrypt.co/368321/bitcoin-etfs-shed-649m-in-a-day-as-long-term-btc-holders-limit-downside-potential",
          "published_at": "2026-05-19T11:55:54+00:00",
          "category": "macro",
          "direction": "bearish",
          "severity": 0.7,
          "confidence": 0.9,
          "cooldown_hours": 72,
          "affected_assets": [
            "BTC"
          ],
          "rationale": "Significant outflows from Bitcoin ETFs represent a broad market event impacting Bitcoin's price.",
          "classified_at": "2026-05-21T02:09:58.644313+00:00"
        },
        {
          "external_id": "https://decrypt.co/?p=368347",
          "title": "Bitcoin Giant Strategy Gets Price Target Boost From TD Cowen After $2 Billion BTC Buy",
          "source": "Decrypt",
          "url": "https://decrypt.co/368347/bitcoin-giant-strategy-price-target-boost-td-cowen-2-billion-btc-buy",
          "published_at": "2026-05-19T15:08:53+00:00",
          "category": "macro",
          "direction": "bullish",
          "severity": 0.65,
          "confidence": 0.9,
          "cooldown_hours": 72,
          "affected_assets": [
            "BTC",
            "MSTR"
          ],
          "rationale": "MicroStrategy's significant $2 billion Bitcoin purchase and the subsequent analyst price target boost for the company reflect strong institutional capital inflow and positive sentiment for Bitcoin, impacting the broader market.",
          "classified_at": "2026-05-21T02:09:53.450530+00:00"
        },
        {
          "external_id": "https://cointelegraph.com/markets/bitcoin-rallies-through-77k-despite-spot-btc-etf-outflows-topping-2b",
          "title": "Bitcoin rallies through $77K despite spot BTC ETF outflows topping $2B",
          "source": "Cointelegraph.com News",
          "url": "https://cointelegraph.com/markets/bitcoin-rallies-through-77k-despite-spot-btc-etf-outflows-topping-2b?utm_source=rss_feed&utm_medium=rss&utm_campaign=rss_partner_inbound",
          "published_at": "2026-05-20T21:22:03+00:00",
          "category": "macro",
          "direction": "bullish",
          "severity": 0.5,
          "confidence": 0.9,
          "cooldown_hours": 72,
          "affected_assets": [
            "BTC"
          ],
          "rationale": "The news describes Bitcoin's price action and market resilience despite significant ETF outflows, indicating a broader market dynamic or sentiment shift.",
          "classified_at": "2026-05-21T02:01:11.486914+00:00"
        }
      ]
    },
    {
      "asset": "MSTR",
      "window_start": "2026-05-21T02:09:53.450530+00:00",
      "window_end": "2026-05-24T02:09:53.450530+00:00",
      "risk_score": 0.585,
      "recommendation": "CAUTION",
      "active_categories": [
        "macro"
      ],
      "computed_at": "2026-05-21T02:09:58.666421+00:00",
      "contributing": [
        {
          "external_id": "https://decrypt.co/?p=368347",
          "title": "Bitcoin Giant Strategy Gets Price Target Boost From TD Cowen After $2 Billion BTC Buy",
          "source": "Decrypt",
          "url": "https://decrypt.co/368347/bitcoin-giant-strategy-price-target-boost-td-cowen-2-billion-btc-buy",
          "published_at": "2026-05-19T15:08:53+00:00",
          "category": "macro",
          "direction": "bullish",
          "severity": 0.65,
          "confidence": 0.9,
          "cooldown_hours": 72,
          "affected_assets": [
            "BTC",
            "MSTR"
          ],
          "rationale": "MicroStrategy's significant $2 billion Bitcoin purchase and the subsequent analyst price target boost for the company reflect strong institutional capital inflow and positive sentiment for Bitcoin, impacting the broader market.",
          "classified_at": "2026-05-21T02:09:53.450530+00:00"
        }
      ]
    },
    {
      "asset": "ETH",
      "window_start": "2026-05-21T02:01:02.234564+00:00",
      "window_end": "2026-05-28T02:01:02.234564+00:00",
      "risk_score": 0.45,
      "recommendation": "CAUTION",
      "active_categories": [
        "protocol_upgrade"
      ],
      "computed_at": "2026-05-21T02:09:58.666421+00:00",
      "contributing": [
        {
          "external_id": "b986c70f-2af9-4a19-b3a3-32b78ba2f642",
          "title": "Vitalik Buterin outlines Ethereum's privacy measures. Here is what it means for the network and ETH",
          "source": "CoinDesk: Bitcoin, Ethereum, Crypto News and Price Data",
          "url": "https://www.coindesk.com/tech/2026/05/20/vitalik-buterin-outlines-ethereum-s-privacy-measures-here-is-what-it-means-for-the-network-and-eth",
          "published_at": "2026-05-20T14:08:09+00:00",
          "category": "protocol_upgrade",
          "direction": "bullish",
          "severity": 0.5,
          "confidence": 0.9,
          "cooldown_hours": 168,
          "affected_assets": [
            "ETH"
          ],
          "rationale": "The news describes a key developer outlining future technical enhancements for the network, which falls under protocol development.",
          "classified_at": "2026-05-21T02:01:02.234564+00:00"
        }
      ]
    }
  ],
  "classifications": [
    {
      "external_id": "https://decrypt.co/?p=368321",
      "title": "Bitcoin ETFs Shed $649M in a Day as Long-Term BTC Holders \u2018Limit Downside Potential\u2019",
      "source": "Decrypt",
      "url": "https://decrypt.co/368321/bitcoin-etfs-shed-649m-in-a-day-as-long-term-btc-holders-limit-downside-potential",
      "published_at": "2026-05-19T11:55:54+00:00",
      "category": "macro",
      "direction": "bearish",
      "severity": 0.7,
      "confidence": 0.9,
      "cooldown_hours": 72,
      "affected_assets": [
        "BTC"
      ],
      "rationale": "Significant outflows from Bitcoin ETFs represent a broad market event impacting Bitcoin's price.",
      "classified_at": "2026-05-21T02:09:58.644313+00:00"
    },
    {
      "external_id": "https://decrypt.co/?p=368347",
      "title": "Bitcoin Giant Strategy Gets Price Target Boost From TD Cowen After $2 Billion BTC Buy",
      "source": "Decrypt",
      "url": "https://decrypt.co/368347/bitcoin-giant-strategy-price-target-boost-td-cowen-2-billion-btc-buy",
      "published_at": "2026-05-19T15:08:53+00:00",
      "category": "macro",
      "direction": "bullish",
      "severity": 0.65,
      "confidence": 0.9,
      "cooldown_hours": 72,
      "affected_assets": [
        "BTC",
        "MSTR"
      ],
      "rationale": "MicroStrategy's significant $2 billion Bitcoin purchase and the subsequent analyst price target boost for the company reflect strong institutional capital inflow and positive sentiment for Bitcoin, impacting the broader market.",
      "classified_at": "2026-05-21T02:09:53.450530+00:00"
    },
    {
      "external_id": "https://cointelegraph.com/markets/solana-futures-funding-rate-turns-negative-is-a-drop-to-78-next",
      "title": "Solana futures funding rate turns negative: Is $78 SOL next?",
      "source": "Cointelegraph.com News",
      "url": "https://cointelegraph.com/markets/solana-futures-funding-rate-turns-negative-is-a-drop-to-78-next?utm_source=rss_feed&utm_medium=rss&utm_campaign=rss_partner_inbound",
      "published_at": "2026-05-20T00:15:57+00:00",
      "category": "noise",
      "direction": "bearish",
      "severity": 0.05,
      "confidence": 0.95,
      "cooldown_hours": 0,
      "affected_assets": [
        "SOL"
      ],
      "rationale": "The news item discusses market indicators and price speculation, which falls under noise as it lacks a concrete operational catalyst.",
      "classified_at": "2026-05-21T02:09:37.569631+00:00"
    },
    {
      "external_id": "https://cointelegraph.com/markets/ethereum-traders-warn-of-a-nasty-eth-price-drop-if-2k-breaks",
      "title": "Ethereum traders warn of a \u2018nasty\u2019 ETH price drop if $2K support breaks",
      "source": "Cointelegraph.com News",
      "url": "https://cointelegraph.com/markets/ethereum-traders-warn-of-a-nasty-eth-price-drop-if-2k-breaks?utm_source=rss_feed&utm_medium=rss&utm_campaign=rss_partner_inbound",
      "published_at": "2026-05-20T14:50:59+00:00",
      "category": "noise",
      "direction": "bearish",
      "severity": 0.05,
      "confidence": 0.95,
      "cooldown_hours": 0,
      "affected_assets": [
        "ETH"
      ],
      "rationale": "The news item is speculative price commentary about a potential price drop and does not represent a concrete operational catalyst.",
      "classified_at": "2026-05-21T02:09:30.289386+00:00"
    },
    {
      "external_id": "https://cointelegraph.com/markets/price-predictions-520-btc-eth-bnb-xrp-sol-doge-hype-ada-zec-bch",
      "title": "Price predictions 5/20: BTC, ETH, BNB, XRP, SOL, DOGE, HYPE, ADA, ZEC, BCH",
      "source": "Cointelegraph.com News",
      "url": "https://cointelegraph.com/markets/price-predictions-520-btc-eth-bnb-xrp-sol-doge-hype-ada-zec-bch?utm_source=rss_feed&utm_medium=rss&utm_campaign=rss_partner_inbound",
      "published_at": "2026-05-20T19:36:38+00:00",
      "category": "noise",
      "direction": "neutral",
      "severity": 0.05,
      "confidence": 0.95,
      "cooldown_hours": 0,
      "affected_assets": [
        "BTC",
        "ETH",
        "BNB",
        "XRP",
        "SOL",
        "DOGE",
        "HYPE",
        "ADA",
        "ZEC",
        "BCH"
      ],
      "rationale": "The news item is a price prediction article, which is speculative and lacks a concrete operational catalyst.",
      "classified_at": "2026-05-21T02:01:15.880235+00:00"
    },
    {
      "external_id": "https://cointelegraph.com/markets/bitcoin-rallies-through-77k-despite-spot-btc-etf-outflows-topping-2b",
      "title": "Bitcoin rallies through $77K despite spot BTC ETF outflows topping $2B",
      "source": "Cointelegraph.com News",
      "url": "https://cointelegraph.com/markets/bitcoin-rallies-through-77k-despite-spot-btc-etf-outflows-topping-2b?utm_source=rss_feed&utm_medium=rss&utm_campaign=rss_partner_inbound",
      "published_at": "2026-05-20T21:22:03+00:00",
      "category": "macro",
      "direction": "bullish",
      "severity": 0.5,
      "confidence": 0.9,
      "cooldown_hours": 72,
      "affected_assets": [
        "BTC"
      ],
      "rationale": "The news describes Bitcoin's price action and market resilience despite significant ETF outflows, indicating a broader market dynamic or sentiment shift.",
      "classified_at": "2026-05-21T02:01:11.486914+00:00"
    },
    {
      "external_id": "b986c70f-2af9-4a19-b3a3-32b78ba2f642",
      "title": "Vitalik Buterin outlines Ethereum's privacy measures. Here is what it means for the network and ETH",
      "source": "CoinDesk: Bitcoin, Ethereum, Crypto News and Price Data",
      "url": "https://www.coindesk.com/tech/2026/05/20/vitalik-buterin-outlines-ethereum-s-privacy-measures-here-is-what-it-means-for-the-network-and-eth",
      "published_at": "2026-05-20T14:08:09+00:00",
      "category": "protocol_upgrade",
      "direction": "bullish",
      "severity": 0.5,
      "confidence": 0.9,
      "cooldown_hours": 168,
      "affected_assets": [
        "ETH"
      ],
      "rationale": "The news describes a key developer outlining future technical enhancements for the network, which falls under protocol development.",
      "classified_at": "2026-05-21T02:01:02.234564+00:00"
    }
  ],
  "category_mix": [
    {
      "category": "macro",
      "count": 3
    },
    {
      "category": "noise",
      "count": 3
    },
    {
      "category": "protocol_upgrade",
      "count": 1
    }
  ],
  "direction_mix": [
    {
      "direction": "bearish",
      "count": 3
    },
    {
      "direction": "bullish",
      "count": 3
    },
    {
      "direction": "neutral",
      "count": 1
    }
  ],
  "source_mix": [
    {
      "source": "Cointelegraph.com News",
      "count": 4
    },
    {
      "source": "Decrypt",
      "count": 2
    },
    {
      "source": "CoinDesk: Bitcoin, Ethereum, Crypto News and Price Data",
      "count": 1
    }
  ]
};
